// Layer Registry header
//
// This file is auto-generated by cmake, don't edit it.

#if TMTOOL_STRING
{"AbsVal",AbsVal_final_layer_creator},
#else
{AbsVal_final_layer_creator},
#endif
#if TMTOOL_STRING
{"ArgMax",0},
#else
{0},
#endif
#if TMTOOL_STRING
{"BatchNorm",BatchNorm_final_layer_creator},
#else
{BatchNorm_final_layer_creator},
#endif
#if TMTOOL_STRING
{"Bias",Bias_final_layer_creator},
#else
{Bias_final_layer_creator},
#endif
#if TMTOOL_STRING
{"BNLL",BNLL_final_layer_creator},
#else
{BNLL_final_layer_creator},
#endif
#if TMTOOL_STRING
{"Concat",Concat_final_layer_creator},
#else
{Concat_final_layer_creator},
#endif
#if TMTOOL_STRING
{"Convolution",Convolution_final_layer_creator},
#else
{Convolution_final_layer_creator},
#endif
#if TMTOOL_STRING
{"Crop",Crop_final_layer_creator},
#else
{Crop_final_layer_creator},
#endif
#if TMTOOL_STRING
{"Deconvolution",Deconvolution_final_layer_creator},
#else
{Deconvolution_final_layer_creator},
#endif
#if TMTOOL_STRING
{"Dropout",Dropout_final_layer_creator},
#else
{Dropout_final_layer_creator},
#endif
#if TMTOOL_STRING
{"Eltwise",Eltwise_final_layer_creator},
#else
{Eltwise_final_layer_creator},
#endif
#if TMTOOL_STRING
{"ELU",ELU_final_layer_creator},
#else
{ELU_final_layer_creator},
#endif
#if TMTOOL_STRING
{"Embed",Embed_final_layer_creator},
#else
{Embed_final_layer_creator},
#endif
#if TMTOOL_STRING
{"Exp",Exp_final_layer_creator},
#else
{Exp_final_layer_creator},
#endif
#if TMTOOL_STRING
{"Flatten",Flatten_final_layer_creator},
#else
{Flatten_final_layer_creator},
#endif
#if TMTOOL_STRING
{"InnerProduct",InnerProduct_final_layer_creator},
#else
{InnerProduct_final_layer_creator},
#endif
#if TMTOOL_STRING
{"Input",Input_final_layer_creator},
#else
{Input_final_layer_creator},
#endif
#if TMTOOL_STRING
{"Log",Log_final_layer_creator},
#else
{Log_final_layer_creator},
#endif
#if TMTOOL_STRING
{"LRN",LRN_final_layer_creator},
#else
{LRN_final_layer_creator},
#endif
#if TMTOOL_STRING
{"MemoryData",MemoryData_final_layer_creator},
#else
{MemoryData_final_layer_creator},
#endif
#if TMTOOL_STRING
{"MVN",MVN_final_layer_creator},
#else
{MVN_final_layer_creator},
#endif
#if TMTOOL_STRING
{"Pooling",Pooling_final_layer_creator},
#else
{Pooling_final_layer_creator},
#endif
#if TMTOOL_STRING
{"Power",Power_final_layer_creator},
#else
{Power_final_layer_creator},
#endif
#if TMTOOL_STRING
{"PReLU",PReLU_final_layer_creator},
#else
{PReLU_final_layer_creator},
#endif
#if TMTOOL_STRING
{"Proposal",Proposal_final_layer_creator},
#else
{Proposal_final_layer_creator},
#endif
#if TMTOOL_STRING
{"Reduction",Reduction_final_layer_creator},
#else
{Reduction_final_layer_creator},
#endif
#if TMTOOL_STRING
{"ReLU",ReLU_final_layer_creator},
#else
{ReLU_final_layer_creator},
#endif
#if TMTOOL_STRING
{"Reshape",Reshape_final_layer_creator},
#else
{Reshape_final_layer_creator},
#endif
#if TMTOOL_STRING
{"ROIPooling",ROIPooling_final_layer_creator},
#else
{ROIPooling_final_layer_creator},
#endif
#if TMTOOL_STRING
{"Region",Region_final_layer_creator},
#else
{Region_final_layer_creator},
#endif
#if TMTOOL_STRING
{"Scale",Scale_final_layer_creator},
#else
{Scale_final_layer_creator},
#endif
#if TMTOOL_STRING
{"Sigmoid",Sigmoid_final_layer_creator},
#else
{Sigmoid_final_layer_creator},
#endif
#if TMTOOL_STRING
{"Slice",Slice_final_layer_creator},
#else
{Slice_final_layer_creator},
#endif
#if TMTOOL_STRING
{"Softmax",Softmax_final_layer_creator},
#else
{Softmax_final_layer_creator},
#endif
#if TMTOOL_STRING
{"Split",Split_final_layer_creator},
#else
{Split_final_layer_creator},
#endif
#if TMTOOL_STRING
{"SPP",0},
#else
{0},
#endif
#if TMTOOL_STRING
{"TanH",TanH_final_layer_creator},
#else
{TanH_final_layer_creator},
#endif
#if TMTOOL_STRING
{"Threshold",Threshold_final_layer_creator},
#else
{Threshold_final_layer_creator},
#endif
#if TMTOOL_STRING
{"Tile",0},
#else
{0},
#endif
#if TMTOOL_STRING
{"RNN",0},
#else
{0},
#endif
#if TMTOOL_STRING
{"LSTM",0},
#else
{0},
#endif
#if TMTOOL_STRING
{"BinaryOp",BinaryOp_final_layer_creator},
#else
{BinaryOp_final_layer_creator},
#endif
#if TMTOOL_STRING
{"UnaryOp",UnaryOp_final_layer_creator},
#else
{UnaryOp_final_layer_creator},
#endif
#if TMTOOL_STRING
{"ConvolutionDepthWise",ConvolutionDepthWise_final_layer_creator},
#else
{ConvolutionDepthWise_final_layer_creator},
#endif
#if TMTOOL_STRING
{"Padding",Padding_final_layer_creator},
#else
{Padding_final_layer_creator},
#endif
#if TMTOOL_STRING
{"Squeeze",Squeeze_final_layer_creator},
#else
{Squeeze_final_layer_creator},
#endif
#if TMTOOL_STRING
{"ExpandDims",ExpandDims_final_layer_creator},
#else
{ExpandDims_final_layer_creator},
#endif
#if TMTOOL_STRING
{"Normalize",Normalize_final_layer_creator},
#else
{Normalize_final_layer_creator},
#endif
#if TMTOOL_STRING
{"Permute",Permute_final_layer_creator},
#else
{Permute_final_layer_creator},
#endif
#if TMTOOL_STRING
{"PriorBox",PriorBox_final_layer_creator},
#else
{PriorBox_final_layer_creator},
#endif
#if TMTOOL_STRING
{"DetectionOutput",DetectionOutput_final_layer_creator},
#else
{DetectionOutput_final_layer_creator},
#endif
#if TMTOOL_STRING
{"Interp",Interp_final_layer_creator},
#else
{Interp_final_layer_creator},
#endif
#if TMTOOL_STRING
{"DeconvolutionDepthWise",DeconvolutionDepthWise_final_layer_creator},
#else
{DeconvolutionDepthWise_final_layer_creator},
#endif
#if TMTOOL_STRING
{"ShuffleChannel",ShuffleChannel_final_layer_creator},
#else
{ShuffleChannel_final_layer_creator},
#endif
#if TMTOOL_STRING
{"InstanceNorm",InstanceNorm_final_layer_creator},
#else
{InstanceNorm_final_layer_creator},
#endif
#if TMTOOL_STRING
{"Clip",Clip_final_layer_creator},
#else
{Clip_final_layer_creator},
#endif
#if TMTOOL_STRING
{"Reorg",Reorg_final_layer_creator},
#else
{Reorg_final_layer_creator},
#endif
#if TMTOOL_STRING
{"YoloDetectionOutput",YoloDetectionOutput_final_layer_creator},
#else
{YoloDetectionOutput_final_layer_creator},
#endif
#if TMTOOL_STRING
{"Quantize",Quantize_final_layer_creator},
#else
{Quantize_final_layer_creator},
#endif
#if TMTOOL_STRING
{"Dequantize",Dequantize_final_layer_creator},
#else
{Dequantize_final_layer_creator},
#endif
#if TMTOOL_STRING
{"Yolov3DetectionOutput",Yolov3DetectionOutput_final_layer_creator},
#else
{Yolov3DetectionOutput_final_layer_creator},
#endif
#if TMTOOL_STRING
{"PSROIPooling",PSROIPooling_final_layer_creator},
#else
{PSROIPooling_final_layer_creator},
#endif
#if TMTOOL_STRING
{"ROIAlign",0},
#else
{0},
#endif
#if TMTOOL_STRING
{"Packing",Packing_final_layer_creator},
#else
{Packing_final_layer_creator},
#endif
#if TMTOOL_STRING
{"Requantize",Requantize_final_layer_creator},
#else
{Requantize_final_layer_creator},
#endif
#if TMTOOL_STRING
{"Cast",Cast_final_layer_creator},
#else
{Cast_final_layer_creator},
#endif
#if TMTOOL_STRING
{"HardSigmoid",HardSigmoid_final_layer_creator},
#else
{HardSigmoid_final_layer_creator},
#endif
#if TMTOOL_STRING
{"SELU",SELU_final_layer_creator},
#else
{SELU_final_layer_creator},
#endif
#if TMTOOL_STRING
{"Upsample",Upsample_final_layer_creator},
#else
{Upsample_final_layer_creator},
#endif
#if TMTOOL_STRING
{"Yolov3DetectionModifiedOutput",Yolov3DetectionModifiedOutput_final_layer_creator},
#else
{Yolov3DetectionModifiedOutput_final_layer_creator},
#endif

